version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: edutrack-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: edutrack_db
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

  mongodb:
    image: mongo:7.0
    container_name: edutrack-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
